FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir streamlit==1.36.0 requests==2.31.0

# Copy Streamlit frontend logic
COPY app.py .

EXPOSE 8501

ENV STREAMLIT_SERVER_PORT=8501
ENV STREAMLIT_SERVER_ADDRESS=0.0.0.0

CMD ["streamlit", "run", "app.py"]
